name: CI

on:
  push:
    branches: [ "main" ]
    tags: [v0.*]
  pull_request:
    branches: [ "main" ]

jobs:
  windows_x86_64:

    name: Build MDRS Windows x86_64
    runs-on: windows-latest
    
    env:
      VPX_STATIC: 1
      VPX_VERSION: 1.8.2
      VPX_LIB_DIR: ${{github.workspace}}\libvpx\lib\x64
      VPX_INCLUDE_DIR: ${{github.workspace}}\libvpx\include

    steps:
    - uses: actions/checkout@v3
    
    - name: caching
      uses: Swatinem/rust-cache@v1
      with:
        key: windows-x86-64-b

    - name: download and extract libvpx
      run: |
        curl -sSfL -O https://github.com/ShiftMediaProject/libvpx/releases/download/v1.8.2/libvpx_v1.8.2_msvc16.zip
        mkdir ${{github.workspace}}\libvpx
        unzip libvpx_v1.8.2_msvc16.zip -d ${{github.workspace}}\libvpx
    
    - name: Build Service
      run: cargo build --release --bin mdrs
    
    - uses: actions/upload-artifact@v3
      with:
        name: mdrs_windows_x86_64
        path: target/release/mdrs.exe

  ubuntu_x86_64:

    name: Build MDRS Ubuntu x86_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: caching
      uses: Swatinem/rust-cache@v1
      with:
        key: ubuntu-x86-64-b

    - name: download and extract libvpx
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libvpx-dev libxcb-randr0-dev
    
    - name: Build Service
      run: cargo build --release --bin mdrs
    
    - uses: actions/upload-artifact@v3
      with:
        name: mdrs_ubuntu_x86_64
        path: target/release/mdrs
  
  macos-x86_64:
    env:
      VPX_STATIC: 1
      VPX_VERSION: 1.8.2
      VPX_LIB_DIR: /opt/libvpx/1.8.1/lib
      VPX_INCLUDE_DIR: /opt/libvpx/1.8.1/include

    name: Build MDRS MacOS x86_64
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: caching
      uses: Swatinem/rust-cache@v1
      with:
        key: macos-x86-64-b

    - name: download and extract libvpx
      run: |
        cd /tmp
        curl --silent -O -L https://strawlab-cdn.com/assets/libvpx-1.8.1.sierra.bottle.tar.gz
        sudo mkdir -p /opt
        sudo tar xvzf /tmp/libvpx-1.8.1.sierra.bottle.tar.gz -C /opt
    
    - name: Build Service
      run: cargo build --release --bin mdrs
    
    - uses: actions/upload-artifact@v3
      with:
        name: mdrs_macos_x86_64
        path: target/release/mdrs
